(function($){$.fn.linhnguyen=function(options){var defaults={animation:'fadeAndPop',animationspeed:300,closeonbackgroundclick:true,dismissmodalclass:'close-linhnguyen-modal'};var options=$.extend({},defaults,options);return this.each(function(){var modal=$(this),topMeasure=parseInt(modal.css('top')),topOffset=modal.height()+topMeasure,locked=false,modalBG=$('.linhnguyen-modal-bg');if(modalBG.length==0){modalBG=$('<div class="linhnguyen-modal-bg" />').insertAfter(modal);}
modal.bind('linhnguyen:open',function(){modalBG.unbind('click.modalEvent');$('.'+options.dismissmodalclass).unbind('click.modalEvent');if(!locked){lockModal();if(options.animation=="fadeAndPop"){modal.css({'top':$(document).scrollTop()-topOffset,'opacity':0,'visibility':'visible'});modalBG.fadeIn(options.animationspeed/2);modal.delay(options.animationspeed/2).animate({"top":$(document).scrollTop()+topMeasure+'px',"opacity":1},options.animationspeed,unlockModal());}
if(options.animation=="fade"){modal.css({'opacity':0,'visibility':'visible','top':$(document).scrollTop()+topMeasure});modalBG.fadeIn(options.animationspeed/2);modal.delay(options.animationspeed/2).animate({"opacity":1},options.animationspeed,unlockModal());}
if(options.animation=="none"){modal.css({'visibility':'visible','top':$(document).scrollTop()+topMeasure});modalBG.css({"display":"block"});unlockModal()}}
modal.unbind('linhnguyen:open');});modal.bind('linhnguyen:close',function(){if(!locked){lockModal();if(options.animation=="fadeAndPop"){modalBG.delay(options.animationspeed).fadeOut(options.animationspeed);modal.animate({"top":$(document).scrollTop()-topOffset+'px',"opacity":0},options.animationspeed/2,function(){modal.css({'top':topMeasure,'opacity':1,'visibility':'hidden'});unlockModal();});}
if(options.animation=="fade"){modalBG.delay(options.animationspeed).fadeOut(options.animationspeed);modal.animate({"opacity":0},options.animationspeed,function(){modal.css({'opacity':1,'visibility':'hidden','top':topMeasure});unlockModal();});}
if(options.animation=="none"){modal.css({'visibility':'hidden','top':topMeasure});modalBG.css({'display':'none'});}}
modal.unbind('linhnguyen:close');});modal.trigger('linhnguyen:open')
var closeButton=$('.'+options.dismissmodalclass).bind('click.modalEvent',function(){modal.trigger('linhnguyen:close')});if(options.closeonbackgroundclick){modalBG.css({"cursor":"pointer"})
modalBG.bind('click.modalEvent',function(){modal.trigger('linhnguyen:close')});}
$('body').keyup(function(e){if(e.which===27){modal.trigger('linhnguyen:close');}});function unlockModal(){locked=false;}
function lockModal(){locked=true;}});}})(jQuery);$(window).load(function(){if(document.cookie.indexOf("adf")==-1)
{document.cookie="adfpopunder1=adf";var divpopup=document.createElement("div");$(divpopup).attr('id','myModal');$(divpopup).attr('class','linhnguyen-modal');$("body").append(divpopup);$("#myModal").html("<a href='http://www.dautudat.vn/san-pham/alibaba-tan-thanh-center-city-6' target='_blank'><img src='https://4.bp.blogspot.com/-eQJIMzJyhj0/W9EmetbTclI/AAAAAAAAJLQ/WQSjl9WOp5YAnSYo7TYXQqzyKfAiyTlGACLcBGAs/s1600/alibaba-tan-thanh-center-city-tongquan.jpg'/></a>.PHÒNG KINH DOANH 0937 091 291<h2><a class='close-linhnguyen-modal'>X</a></h2>");$('#myModal').linhnguyen($('#myModal').data());}});
